# The command to show all about the database
schemacmd = """
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE'
AND table_schema NOT IN ('information_schema', 'pg_catalog');
"""

import mysql.connector
from mysql.connector import Error
import re

def extract_sql_query(text):
    """
    Extract SQL query from text output generated by LLMs.
    
    Args:
        text (str): The text containing an SQL query
        
    Returns:
        str: The extracted SQL query or None if no query is found
    """
    # Look for SQL between code blocks
    sql_block_pattern = r"```sql\s*(.*?)\s*```"
    matches = re.findall(sql_block_pattern, text, re.DOTALL)
    if matches:
        return matches[0].strip()
    
    # Look for SQL between other code block markers
    code_block_pattern = r"```\s*(.*?)\s*```"
    matches = re.findall(code_block_pattern, text, re.DOTALL)
    if matches:
        # Check if the content looks like SQL
        for match in matches:
            if re.search(r'\b(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\b', match, re.IGNORECASE):
                return match.strip()
    
    # Look for SQL queries that start with SELECT, INSERT, etc. and end with a semicolon
    sql_query_pattern = r"(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)[\s\S]*?;"
    matches = re.findall(sql_query_pattern, text, re.IGNORECASE)
    if matches:
        # Get the full match, not just the capturing group
        full_matches = re.findall(sql_query_pattern, text, re.IGNORECASE | re.DOTALL)
        if full_matches:
            return full_matches[0].strip()
    
    # If all else fails, look for anything that looks like SQL
    potential_sql = re.search(r"(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)[\s\S]*?(;|\Z)", text, re.IGNORECASE | re.DOTALL)
    if potential_sql:
        return potential_sql.group().strip().rstrip(';') + ';'
    
    return None

def run_sql_comparison_pipeline(query1, query2):
    # Configuration
    config = {
        "host": "localhost",
        "user": "root",
        "password": "password",
        "database": "atis"
    }
    
    results1 = None
    results2 = None
    
    # Connect to the database
    try:
        conn = mysql.connector.connect(**config)
        cursor = conn.cursor()
        
        # Execute the first query
        try:
            print(f"Executing query 1: {query1}")
            cursor.execute(query1)
            results1 = cursor.fetchall()
            print(f"Query 1 returned {len(results1)} rows")
        except Error as e:
            print(f"Error executing query 1: {e}")
        
        # Execute the second query
        try:
            print(f"Executing query 2: {query2}")
            cursor.execute(query2)
            results2 = cursor.fetchall()
            print(f"Query 2 returned {len(results2)} rows")
        except Error as e:
            print(f"Error executing query 2: {e}")
        
        # Close connections
        cursor.close()
        conn.close()
        
        # Compare results
        if results1 is not None and results2 is not None:
            # Sort results to make them order-independent
            sorted_results1 = sorted([tuple(row) for row in results1])
            sorted_results2 = sorted([tuple(row) for row in results2])
            
            if len(sorted_results1) != len(sorted_results2):
                print("RESULT: DIFFERENT - Queries returned different number of rows")
                print(f"Query 1: {len(results1)} rows")
                print(f"Query 2: {len(results2)} rows")
            elif sorted_results1 == sorted_results2:
                if results1 == results2:
                    print("RESULT: SAME - Both queries returned identical results in the same order")
                else:
                    print("RESULT: SAME DATA, DIFFERENT ORDER - Both queries returned the same data but in different order")
            else:
                print("RESULT: DIFFERENT - Queries returned different results")
            
            # Display results
            print("\nResults from Query 1:")
            for row in results1[:10]:  # Limit to first 10 rows
                print(row)
            
            if len(results1) > 10:
                print(f"...and {len(results1) - 10} more rows")
                
            print("\nResults from Query 2:")
            for row in results2[:10]:  # Limit to first 10 rows
                print(row)
            
            if len(results2) > 10:
                print(f"...and {len(results2) - 10} more rows")
        else:
            print("RESULT: CANNOT COMPARE - One or both queries failed to execute")
            
    except Error as e:
        print(f"Database connection error: {e}")